services:
  mars-test-runner:
    build: ./source/mars-ingestion-service
    container_name: mars-test-runner
    environment:
      - MARS_SIMULATOR_URL=http://host.docker.internal:8080
    command: ["java", "-cp", "app.jar", "com.mars.tester.MarsApiTester"]
    depends_on:
      - mars-simulator
    network_mode: host

  mars-simulator:
    image: mars-iot-simulator:multiarch_v1
    ports:
      - "8080:8080"
    container_name: mars-simulator
